- name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-chromedriver: true

- name: Output Chrome Info
  run: |
    google-chrome --version
    chromedriver --version
